// Master schema that re-exports both Better Auth and application schemas
// This prevents conflicts when Better Auth regenerates auth-schema.ts

// Better Auth tables (ba_ prefixed to avoid conflicts)
export * from "./schema.auth";

// Application tables (importing ALL tables with aliases for conflicting names)
export {
  // Enums
  accountRole,
  appPermissions,
  billingProvider,
  billingProviders,
  chatRole,
  difficulty,
  invitationStatus,
  invitationType,
  notificationChannel,
  notificationType,
  paymentStatus,
  pricingPlanInterval,
  pricingType,
  roleStatus,
  subscriptionItemType,
  subscriptionStatus,
  taskstate,
  tasktype,

  // Application tables (all tables)
  assessments,
  activities,
  prismaMigrations,
  profiles,
  answers,
  categories,
  constants,
  goals,
  imageSearch,
  obstacles,
  profilesCopy,
  evaluations,
  lcaInvitations,
  gameInfo,
  activityProgress,
  questions,
  scores,
  gameTasks,
  sizes,
  status,
  taskCompletion,
  userTasks,
  vendorRatings,
  visionBoards,
  visionLog,
  config,
  roles,
  rolePermissions,
  billingCustomers,
  subscriptions,
  subscriptionItems,
  orders,
  orderItems,
  accountUser,
  notifications,
  chats,
  tasks,
  chatMessages,
  creditsUsage,
  plans,
  userSkills,
  userPrograms,
  personalityExams,
  userSkillDetails,
  nonces,
  examTraits,
  examStrengths,
  examGrowthAreas,
  programSkillRequirements,
  accountsMemberships,
  userAccountWorkspace,
  userAccounts,
  userEmloyementStatus,
  workplaceType,
  userEmloyementStatuss,
  answersIdSeq1,
  authUsers,
  workplaces,
  // organizations,

  // Legacy auth tables (aliased to avoid conflicts with Better Auth)
  user as legacyUser,
  session as legacySession,
  account as legacyAccount,
  verification as legacyVerification,
  accounts as legacyAccounts,
  invitations as legacyInvitations,
} from "../../drizzle/schema";
