export * from "./schema.auth";

export {
  // Enums
  accountRole,
  appPermissions,
  billingProvider,
  billingProviders,
  chatRole,
  difficulty,
  invitationStatus,
  invitationType,
  notificationChannel,
  notificationType,
  paymentStatus,
  pricingPlanInterval,
  pricingType,
  roleStatus,
  subscriptionItemType,
  subscriptionStatus,
  taskstate,
  tasktype,

  // Application tables (all tables)
  assessments,
  activities,
  prismaMigrations,
  profiles,
  answers,
  categories,
  constants,
  goals,
  imageSearch,
  obstacles,
  profilesCopy,
  evaluations,
  lcaInvitations,
  gameInfo,
  activityProgress,
  questions,
  scores,
  gameTasks,
  sizes,
  status,
  taskCompletion,
  userTasks,
  vendorRatings,
  visionBoards,
  visionLog,
  config,
  roles,
  rolePermissions,
  billingCustomers,
  subscriptions,
  subscriptionItems,
  orders,
  orderItems,
  accountUser,
  notifications,
  chats,
  tasks,
  chatMessages,
  creditsUsage,
  plans,
  userSkills,
  userPrograms,
  personalityExams,
  userSkillDetails,
  nonces,
  examTraits,
  examStrengths,
  examGrowthAreas,
  programSkillRequirements,
  accountsMemberships,
  userAccountWorkspace,
  userAccounts,
  userEmloyementStatus,
  workplaceType,
  userEmloyementStatuss,
  workplaces,
  // organizations,

  // Legacy auth tables (aliased to avoid conflicts with Better Auth)
  user as legacyUser,
  session as legacySession,
  account as legacyAccount,
  verification as legacyVerification,
  accounts as legacyAccounts,
  invitations as legacyInvitations,

  // Better Auth tables
  baInvitations,
  baUsers,
  baSessions,
  baAccounts,
  baVerifications,
} from "../../drizzle/schema";
