name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && (contains(github.event.comment.body, '@claude') && !contains(github.event.comment.body, '@claude-fix') && !contains(github.event.comment.body, '@claude-optimize'))) ||
      (github.event_name == 'pull_request_review_comment' && (contains(github.event.comment.body, '@claude') && !contains(github.event.comment.body, '@claude-fix') && !contains(github.event.comment.body, '@claude-optimize'))) ||
      (github.event_name == 'pull_request_review' && (contains(github.event.review.body, '@claude') && !contains(github.event.review.body, '@claude-fix') && !contains(github.event.review.body, '@claude-optimize'))) ||
      (github.event_name == 'issues' && ((contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')) && !contains(github.event.issue.body, '@claude-fix') && !contains(github.event.issue.body, '@claude-optimize')))
    runs-on: depot-ubuntu-24.04
    env:
      DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Optional: Allow Claude to run specific commands
          allowed_tools: "Bash(pnpm install),Bash(pnpm run build),Bash(pnpm run test),Bash(pnpm run test:*),Bash(pnpm run lint),Bash(pnpm run typecheck)"
          
          # Optional: Add custom instructions for Claude to customize its behavior for your project
          custom_instructions: |
            This is a Next.js 15 project with App Router using TypeScript and shadcn/ui components.
            
            Key requirements:
            - ALWAYS use pnpm as package manager (never npm or yarn)
            - Use shadcn/ui semantic color utilities (bg-background, text-foreground, etc.) instead of hardcoded colors
            - Follow the incremental approach: Start Small → Validate → Expand → Scale
            - All new components should use 'use client' directive and shadcn/ui patterns
            - Import using @/ alias from src directory
            - Write tests using Jest and React Testing Library before implementation (TDD)
            - Run pnpm build, pnpm lint, and pnpm test before suggesting completion
            
            Check CLAUDE.md and .agent-os/product/ files for detailed project context and standards.
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test

